### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by onlyonewater** [mayu-ot/hidden-challenges-MR#4]
Hi, in the paper, you've relabeled the datasets, which 1000 samples for charades and 1288 samples for activitynet, can you provide them? Thanks!!!

**Comment by mayu-ot** [comment]
Hi, sorry for the late response.
The re-labeled datasets are available in this repository.

https://github.com/mayu-ot/hidden-challenges-MR/tree/master/data/raw/charades/re-annotated
https://github.com/mayu-ot/hidden-challenges-MR/tree/master/data/raw/activitynet/re-annotated

**Comment by onlyonewater** [comment]
Ok, I know, thanks!!!
